feature/issue-45
Byndyusoft/nest-template pull request #88
Opened 2022-09-19 06:30 UTC by step1989

Work within the issue https://github.com/Byndyusoft/nest-template/issues/45

- dotenv was moved from dependencies to devDependencies
- config module was refactoring

2022-09-19 06:51 UTC, nmorgunov submitted a review, later dismissed

2022-10-01 06:36 UTC, KillWolfVlad approved these changes

2022-10-04 06:35 UTC, KillWolfVlad requested changes
Update migrator too

2022-10-06 07:39 UTC, nmorgunov submitted a review, later dismissed

2022-10-22 04:55 UTC, KillWolfVlad approved these changes

2022-10-22 04:59 UTC, merged