feature/issue-91
Byndyusoft/nest-template pull request #92
Opened 2022-10-07 04:22 UTC by step1989

2022-10-08 07:00 UTC, KillWolfVlad requested changes

2022-10-08 07:00 UTC, KillWolfVlad commented on packages/app/package.json
> +      "@casualbot/jest-sonar-reporter"
Return `default` reporter, see https://github.com/CasualBot/jest-sonar-reporter#usage for more usage information.

2022-10-08 07:00 UTC, KillWolfVlad commented on packages/app/package.json
> +  "@casualbot/jest-sonar-reporter": {
Configure reporter via jest, see https://github.com/CasualBot/jest-sonar-reporter#configuration for more usage information.

2022-10-08 09:36 UTC, step1989 commented on packages/app/package.json
> +  "@casualbot/jest-sonar-reporter": {
What parameters do you think are missing?
I think the given options are enough.

2022-10-09 04:29 UTC, KillWolfVlad commented on packages/app/package.json
> +  "@casualbot/jest-sonar-reporter": {
See to the bottom of the README:

```javascript
// jest.config.js
{
    reporters: [
        'default', 
        [ 
            '@casualbot/jest-sonar-reporter',
            {
                relativePaths: true,
                outputName: 'sonar-report.xml',
                outputDirectory: 'coverage'
            }
        ]
    ],
}
```

2022-10-09 05:36 UTC, step1989 commented on packages/app/package.json
> +  "@casualbot/jest-sonar-reporter": {
Do you think your solution is more readable or more correct?
I used a different configuration option. it is working.

it's just above yours
`
"@casualbot/jest-sonar-reporter": {
    "suiteName": "jest tests",
    "outputDirectory": "coverage",
    "outputName": "jest-report.xml",
    "uniqueOutputName": "false",
    "classNameTemplate": "{classname}-{title}",
    "titleTemplate": "{classname}-{title}",
    "ancestorSeparator": " › ",
    "usePathForSuiteName": "true",
    "relativePaths": "true"
  }
`

2022-10-09 06:04 UTC, KillWolfVlad commented on packages/app/package.json
> +  "@casualbot/jest-sonar-reporter": {
I want use configuration via Jest to place all thing as more closer as possible. See how we setup Allure reporter:

```json
{
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "js"
    ],
    "resetMocks": true,
    "rootDir": "./",
    "roots": [
      "<rootDir>/src",
      "<rootDir>/test"
    ],
    "setupFilesAfterEnv": [
      "jest-extended/all",
      "./src/main.ts"
    ],
    "testEnvironment": "jest-allure-circus",
    "testEnvironmentOptions": {
      "jiraUrl": "https://jira.example.com/browse/"
    },
    "testRegex": ".*\\.spec\\.ts$",
    "testTimeout": 60000,
    "transform": {
      "^.+\\.ts$": "ts-jest"
    }
  }
}
```

2022-10-09 13:02 UTC, step1989 commented on packages/app/package.json
> +  "@casualbot/jest-sonar-reporter": {
this is a good argument.
fixed

2022-10-09 13:03 UTC, step1989 commented on packages/app/package.json
> +      "@casualbot/jest-sonar-reporter"
fixed

2022-10-12 06:28 UTC, lalumiere17 approved these changes, later dismissed

2022-10-15 04:20 UTC, KillWolfVlad approved these changes

2022-10-15 05:44 UTC, merged